use std::fs::{self, File};
use std::io::Write;
use std::path::Path;

use crate::constants;

pub fn export_java_constants(path_str: &str) {
    println!("🔄 Generating Java constants to: {}", path_str);
    let path = Path::new(path_str);

    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).unwrap();
    }

    let mut file = File::create(path).expect("Failed to create Java constants file");

    // 调用宏生成的辅助函数
    let definitions = constants::generate_java_definitions();

    let java_content = format!(
        r#"package bind;

/**
 * ⚠️ AUTO-GENERATED FILE. DO NOT EDIT. ⚠️
 *
 * Source: core/src/constants.rs
 * Generated by: core/src/bin/gen_constants.rs
 */
public class GeneratedConstants {{
{}
}}
"#,
        definitions
    );

    file.write_all(java_content.as_bytes()).unwrap();
    println!("✅ Success! Java constants updated.");
}
