use std::fs::{self, File};
use std::io::Write;
use std::path::Path;
use ts_rs::TS;

// 引入所有需要导出的类型
// 假设这些类型都在 crate::vision::types 下
use crate::domain::vision::filters::{
    AutoCropFilter,
    BinarizationFilter,
    BinarizationMode, // 注意这里还需要导出 Mode
    BlackWhiteInvertFilter,
    DenoiseFilter,
    DeskewFilter,
    ExtendCropFilter,
    ExtractBlobsFilter,
    ExtractContoursFilter,
    GrayscaleFilter,
    MorphologyFilter, // 如果有 MorphologyOp 枚举，建议也在此处引入并导出
    MultiColorFilter,
    PosterizationFilter,
    RemoveLinesFilter,
    RemoveNoiseFilter,
    ResizeScaleFilter,
    RotationFilter,
    SmartLayoutFilter,
};
use crate::domain::vision::types::{
    ColorRule, GridParams, ImageFilterWrapper, ProcessedImage, Rect, SegmentationConfig,
    SegmentationMode,
};

pub fn export_ts_types(path_str: &str) {
    println!("🚀 Exporting TypeScript definitions to: {}", path_str);

    let path = Path::new(path_str);

    // 1. 自动创建父目录 (如果不存在)
    if let Some(parent) = path.parent() {
        if !parent.exists() {
            fs::create_dir_all(parent).expect("❌ Failed to create directory for TS types");
        }
    }

    // 2. 创建或覆盖文件
    let mut file = File::create(path).expect("❌ Failed to create TS output file");

    // 3. 写入文件头
    writeln!(file, "/*").unwrap();
    writeln!(file, " * ⚠️ THIS FILE IS AUTO-GENERATED BY RUST").unwrap();
    writeln!(file, " * ⚠️ DO NOT EDIT MANUALLY").unwrap();
    writeln!(
        file,
        " * Run `cargo run --bin gen_ts_types ` to update this file."
    )
    .unwrap();
    writeln!(file, " */\n").unwrap();

    // 禁用 eslint 检查，防止生成的代码格式报错
    writeln!(file, "/* eslint-disable */\n").unwrap();

    // 4. 依次写入各个类型的定义
    // 使用泛型函数简化重复代码
    write_type_decl::<Rect>(&mut file);
    write_type_decl::<ColorRule>(&mut file);
    write_type_decl::<GridParams>(&mut file);
    write_type_decl::<ProcessedImage>(&mut file);
    write_type_decl::<SegmentationMode>(&mut file);
    write_type_decl::<SegmentationConfig>(&mut file);

    // Binarization
    write_type_decl::<BinarizationMode>(&mut file); // 必须导出，否则 TS 报错 "BinarizationMode not defined"
    write_type_decl::<BinarizationFilter>(&mut file);

    // 其他滤镜
    write_type_decl::<PosterizationFilter>(&mut file);
    write_type_decl::<MultiColorFilter>(&mut file);
    write_type_decl::<GrayscaleFilter>(&mut file);
    write_type_decl::<RemoveNoiseFilter>(&mut file);
    write_type_decl::<RemoveLinesFilter>(&mut file);
    write_type_decl::<ExtractContoursFilter>(&mut file);
    write_type_decl::<ExtractBlobsFilter>(&mut file);
    write_type_decl::<DeskewFilter>(&mut file);
    write_type_decl::<RotationFilter>(&mut file);
    write_type_decl::<BlackWhiteInvertFilter>(&mut file);
    write_type_decl::<MorphologyFilter>(&mut file);
    write_type_decl::<SmartLayoutFilter>(&mut file);
    write_type_decl::<AutoCropFilter>(&mut file);
    write_type_decl::<ResizeScaleFilter>(&mut file);
    write_type_decl::<ExtendCropFilter>(&mut file);
    write_type_decl::<DenoiseFilter>(&mut file);

    // 最后导出 Wrapper (它引用了上面所有的 Filter)
    write_type_decl::<ImageFilterWrapper>(&mut file);

    println!("✅ TypeScript bindings generated successfully!");
}

// 辅助函数：将 TS 定义写入文件
fn write_type_decl<T: TS>(file: &mut File) {
    let decl = T::decl();
    // 加上 export 关键字，确保在 d.ts 中可以被 import
    writeln!(file, "export {}\n", decl).expect("Failed to write TS decl");
}
