use std::fs::{self, File};
use std::io::Write;
use std::path::Path;
use ts_rs::TS;

// 引入所有需要导出的类型
// 假设这些类型都在 crate::vision::types 下
use crate::domain::vision::types::{
    ColorRule, GridParams, ImageFilterWrapper, ProcessedImage, Rect, SegmentationConfig,
    SegmentationMode,
};

pub fn export_ts_types(path_str: &str) {
    println!("🚀 Exporting TypeScript definitions to: {}", path_str);

    let path = Path::new(path_str);

    // 1. 自动创建父目录 (如果不存在)
    if let Some(parent) = path.parent() {
        if !parent.exists() {
            fs::create_dir_all(parent).expect("❌ Failed to create directory for TS types");
        }
    }

    // 2. 创建或覆盖文件
    let mut file = File::create(path).expect("❌ Failed to create TS output file");

    // 3. 写入文件头
    writeln!(file, "/*").unwrap();
    writeln!(file, " * ⚠️ THIS FILE IS AUTO-GENERATED BY RUST").unwrap();
    writeln!(file, " * ⚠️ DO NOT EDIT MANUALLY").unwrap();
    writeln!(
        file,
        " * Run `cargo run --bin gen_ts_types ` to update this file."
    )
    .unwrap();
    writeln!(file, " */\n").unwrap();

    // 禁用 eslint 检查，防止生成的代码格式报错
    writeln!(file, "/* eslint-disable */\n").unwrap();

    // 4. 依次写入各个类型的定义
    // 使用泛型函数简化重复代码
    write_type_decl::<Rect>(&mut file);
    write_type_decl::<ColorRule>(&mut file);
    write_type_decl::<GridParams>(&mut file);
    write_type_decl::<ProcessedImage>(&mut file);
    write_type_decl::<SegmentationMode>(&mut file);
    write_type_decl::<SegmentationConfig>(&mut file);

    // ⚠️ 注意：这要求 ImageFilterWrapper 内部引用的所有 Filter (AutoCropFilter等)
    // 也都必须实现了 TS Trait。如果你还没给 filters/*.rs 加宏，先注释掉下面这行。
    write_type_decl::<ImageFilterWrapper>(&mut file);

    println!("✅ TypeScript bindings generated successfully!");
}

// 辅助函数：将 TS 定义写入文件
fn write_type_decl<T: TS>(file: &mut File) {
    let decl = T::decl();
    // 加上 export 关键字，确保在 d.ts 中可以被 import
    writeln!(file, "export {}\n", decl).expect("Failed to write TS decl");
}
