// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Action = { "type": "Click", x: number, y: number, delay_ms: bigint, } | { "type": "Wait", ms: bigint, } | { "type": "Log", msg: string, } | { "type": "FindAndClick", color_html: string, tolerance: number, region: Array<number> | null, };
