package org.eu.freex.server;

/**
 * Auto-generated by Rust (rust_core/src/export.rs).
 * DO NOT EDIT THIS FILE MANUALLY.
 * 修改源头: rust_core/src/constants.rs
 */
public class GeneratedConstants {
    public static final String SHARED_FILE_PATH = "/data/local/tmp/screen_buffer.raw";
    // 使用十六进制格式化，并在 Java 中保留注释说明大小
    public static final byte SIGNAL_BYTE = (byte) 0xAA;
    public static final int SHARED_MEMORY_SIZE = 4194304; // 4 MB
}
