package org.eu.freex.tools.modules.image.application

import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.InternalSerializationApi
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.serializer
import org.eu.freex.tools.common.utils.ImageUtils.binaryStringToHex
import org.eu.freex.tools.modules.image.domain.model.ImageFilter
import org.eu.freex.tools.modules.image.domain.model.Pipeline
import org.eu.freex.tools.modules.image.domain.model.SegmentationConfig
import kotlin.reflect.full.memberProperties

/**
 * TypeScript 代码生成器 (基于 kotlinx.serialization)
 * 能够自动将当前工作台的配置转换为可直接运行的 TouchHelper 脚本
 */
object TsCodeGeneratorUseCase {

    // 配置 JSON 格式：美化输出，确保生成的代码易读
    private val json = Json {
        prettyPrint = true
        encodeDefaults = true      // 输出默认值，确保 TS 端行为一致
        ignoreUnknownKeys = true   // 忽略无关字段
        explicitNulls = false      // 不输出 null 字段，保持简洁
    }

    /**
     * 生成完整脚本
     *
     * @param pipeline 当前滤镜流水线 (包含多个 ImageLayer 步骤)
     * @param segConfig 切割配置
     * @param fontLib 字库 (Map<字符, 特征码>)
     * @param minConf 识别阈值
     */
    @OptIn(InternalSerializationApi::class, ExperimentalSerializationApi::class)
    fun generate(
        pipeline: Pipeline?,
        segConfig: SegmentationConfig?,
        fontLib: Map<String, String>?,
        minConf: Float = 0.8f
    ): String {
        val sb = StringBuilder()

        // 1. 头部引用与初始化
        sb.appendLine("// =============================================")
        sb.appendLine("// 🚀 Auto-Generated by TouchHelper Desktop Tool")
        sb.appendLine("// =============================================")
        sb.appendLine()
        sb.appendLine("import { ImageFilterWrapper, SegmentationConfig } from './types/touch-helper';")
        sb.appendLine()
        sb.appendLine("// 1. 截图")
        sb.appendLine("const img = Device.capture();")
        sb.appendLine()

        // 2. 生成滤镜代码 (修复：从 steps 中提取 activeFilter)
        if (pipeline != null && pipeline.steps.isNotEmpty()) {
            sb.appendLine("// 2. 应用滤镜处理")

            // 过滤出真正包含滤镜的层（有些层可能是原图或其他类型，虽然在 Pipeline 里通常都是滤镜层）
            val filterSteps = pipeline.steps.mapNotNull { it.activeFilter }

            if (filterSteps.isNotEmpty()) {
                filterSteps.forEachIndexed { index, filter ->
                    val stepName = filter::class.simpleName ?: "UnknownFilter"
                    sb.appendLine("// Step ${index + 1}: $stepName")

                    // 核心魔法：将 Kotlin 对象转为符合 TS ImageFilterWrapper 定义的 JSON
                    val wrapperJson = convertFilterToWrapperJson(filter)
                    sb.appendLine("img.applyFilter($wrapperJson);")
                }
            } else {
                sb.appendLine("// (流水线中没有有效的滤镜步骤)")
            }
            sb.appendLine()
        }

        // 3. 生成切割与识别代码
        if (segConfig != null) {
            sb.appendLine("// 3. 配置切割参数")
            // 直接序列化 Config 对象
            // 因为您加了 @Serializable，这里会生成标准的 JSON
            val configJson = this.convertSegmentationToWrapperJson(segConfig)
            sb.appendLine("const config: SegmentationConfig = $configJson;")
            sb.appendLine()

            if (!fontLib.isNullOrEmpty()) {
                sb.appendLine("// 4. 字库数据 (Hex压缩)")

                // 🔥 压缩逻辑：Binary -> Hex Map
                val compressedLib = fontLib.mapValues { (_, binStr) -> binaryStringToHex(binStr) }

                // 生成干净的 Map: { "汉": "HexStr", ... }
                val libJson = json.encodeToString(json.serializersModule.serializer(), compressedLib)
                sb.appendLine("const fontLibrary = $libJson;")

                // Rust 运行时会自动识别 Hex，无需解压代码
                sb.appendLine()
                sb.appendLine("// 5. 执行识别")
                sb.appendLine("const result = img.ocrGrid(config, fontLibrary, $minConf);")
                sb.appendLine($$"log(`识别结果: ${result}`);")
            }
        }

        // 4. 结尾清理建议
        sb.appendLine()
        sb.appendLine("// 提示: 如果在循环中使用，请记得手动回收图片资源")
        sb.appendLine("// img.recycle();")

        return sb.toString()
    }

    @OptIn(InternalSerializationApi::class)
    private fun convertSegmentationToWrapperJson(segConfig: SegmentationConfig): String {

        // 🔥 修改开始：转为 Rust 对象 -> 转 JSON 树 -> 递归修复枚举 -> 转字符串
        val rustConfig = segConfig.toRust()
        // 获取 Rust 类的序列化器
        @Suppress("UNCHECKED_CAST")
        val configSerializer = rustConfig::class.serializer() as kotlinx.serialization.KSerializer<Any>

        // 生成 JSON 树并修复枚举 (FIXED_GRID -> fixedGrid)
        val configJsonElement = json.encodeToJsonElement(configSerializer, rustConfig)
        val fixedConfigJson = fixEnumsRecursively(configJsonElement)

        // 输出
        return json.encodeToString(JsonElement.serializer(), fixedConfigJson)
    }

    @InternalSerializationApi
    private fun convertFilterToWrapperJson(uiFilter: ImageFilter): String {
        val className = uiFilter::class.simpleName ?: return "{}"
        // Wrapper Key: "BinarizationFilter" -> "binarization"
        val keyName = className.removeSuffix("Filter").replaceFirstChar { it.lowercase() }

        // 1. 拆包获取 Rust Struct (如 uniffi...BinarizationFilter)
        val rustWrapper = uiFilter.toRust()
        val rustStruct = unwrapUniffiEnum(rustWrapper) ?: return "{}"

        // 2. 获取序列化器
        @Suppress("UNCHECKED_CAST")
        val serializer = rustStruct::class.serializer() as kotlinx.serialization.KSerializer<Any>

        // 3. 🔥 [核心修改]：先转成 JSON 树，而不是直接转字符串
        val jsonTree = json.encodeToJsonElement(serializer, rustStruct)

        // 4. 🔥 [核心修改]：递归修正枚举值的格式 (MANUAL -> manual, AUTO_TO_WHITE -> autoToWhite)
        val fixedJsonTree = fixEnumsRecursively(jsonTree)

        // 5. 输出最终字符串
        val filterJsonString = json.encodeToString(JsonElement.serializer(), fixedJsonTree)

        return """{ "$keyName": $filterJsonString }"""
    }

    // ========================================================================
    // 👇 新增的两个辅助函数，用于自动修正枚举格式
    // ========================================================================

    /**
     * 递归遍历 JSON 树，将所有全大写的字符串值转换为 camelCase
     */
    private fun fixEnumsRecursively(element: JsonElement): JsonElement {
        return when (element) {
            is JsonObject -> JsonObject(element.mapValues { fixEnumsRecursively(it.value) })
            is JsonArray -> JsonArray(element.map { fixEnumsRecursively(it) })
            is JsonPrimitive -> {
                if (element.isString) {
                    val str = element.content
                    // 规则：如果字符串全是 [A-Z_]，则认为是枚举，需要转换
                    // 例如: "AUTO_TO_WHITE_BG" -> "autoToWhiteBg", "FORCE" -> "force"
                    if (str.isNotEmpty() && str.all { it.isUpperCase() || it == '_' }) {
                        JsonPrimitive(snakeToCamel(str))
                    } else {
                        element
                    }
                } else {
                    element
                }
            }
        }
    }

    /**
     * 字符串转换算法: SCREAMING_SNAKE_CASE -> camelCase
     * 例: "AUTO_TO_WHITE_BG" -> "autoToWhiteBg"
     * 例: "FORCE" -> "force"
     */
    private fun snakeToCamel(input: String): String {
        return input.lowercase().split('_').mapIndexed { index, part ->
            if (index == 0) part else part.replaceFirstChar { it.uppercase() }
        }.joinToString("")
    }

    /**
     * 辅助函数：利用反射取出 UniFFI 枚举变体中的数据对象
     * 避免了写巨大的 when (wrapper) { is Binarization -> wrapper.v1 ... }
     */
    private fun unwrapUniffiEnum(wrapper: Any): Any? {
        try {
            // 获取该对象的所有属性
            val props = wrapper::class.memberProperties
            // UniFFI 生成的元组枚举变体通常只有一个属性来持有数据
            if (props.size == 1) {
                // 取出第一个属性的值
                return props.first().call(wrapper)
            }
        } catch (e: Exception) {
            e.printStackTrace()
        }
        return null
    }
}