package org.eu.freex.tools.modules.image.application

import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.InternalSerializationApi
import kotlinx.serialization.json.Json
import kotlinx.serialization.serializer
import org.eu.freex.tools.common.utils.ImageUtils.binaryStringToHex
import org.eu.freex.tools.modules.image.domain.model.ImageFilter
import org.eu.freex.tools.modules.image.domain.model.Pipeline
import org.eu.freex.tools.modules.image.domain.model.SegmentationConfig

/**
 * TypeScript 代码生成器 (基于 kotlinx.serialization)
 * 能够自动将当前工作台的配置转换为可直接运行的 TouchHelper 脚本
 */
object TsCodeGeneratorUseCase {

    // 配置 JSON 格式：美化输出，确保生成的代码易读
    private val json = Json {
        prettyPrint = true
        encodeDefaults = true      // 输出默认值，确保 TS 端行为一致
        ignoreUnknownKeys = true   // 忽略无关字段
        explicitNulls = false      // 不输出 null 字段，保持简洁
    }

    /**
     * 生成完整脚本
     *
     * @param pipeline 当前滤镜流水线 (包含多个 ImageLayer 步骤)
     * @param segConfig 切割配置
     * @param fontLib 字库 (Map<字符, 特征码>)
     * @param minConf 识别阈值
     */
    @OptIn(InternalSerializationApi::class, ExperimentalSerializationApi::class)
    fun generate(
        pipeline: Pipeline?,
        segConfig: SegmentationConfig?,
        fontLib: Map<String, String>?,
        minConf: Float = 0.8f
    ): String {
        val sb = StringBuilder()

        // 1. 头部引用与初始化
        sb.appendLine("// =============================================")
        sb.appendLine("// 🚀 Auto-Generated by TouchHelper Desktop Tool")
        sb.appendLine("// =============================================")
        sb.appendLine()
        sb.appendLine("import { ImageFilterWrapper, SegmentationConfig } from './types/touch-helper';")
        sb.appendLine()
        sb.appendLine("// 1. 截图")
        sb.appendLine("const img = device.capture();")
        sb.appendLine()

        // 2. 生成滤镜代码 (修复：从 steps 中提取 activeFilter)
        if (pipeline != null && pipeline.steps.isNotEmpty()) {
            sb.appendLine("// 2. 应用滤镜处理")

            // 过滤出真正包含滤镜的层（有些层可能是原图或其他类型，虽然在 Pipeline 里通常都是滤镜层）
            val filterSteps = pipeline.steps.mapNotNull { it.activeFilter }

            if (filterSteps.isNotEmpty()) {
                filterSteps.forEachIndexed { index, filter ->
                    val stepName = filter::class.simpleName ?: "UnknownFilter"
                    sb.appendLine("// Step ${index + 1}: $stepName")

                    // 核心魔法：将 Kotlin 对象转为符合 TS ImageFilterWrapper 定义的 JSON
                    val wrapperJson = convertFilterToWrapperJson(filter)
                    sb.appendLine("img.applyFilter($wrapperJson);")
                }
            } else {
                sb.appendLine("// (流水线中没有有效的滤镜步骤)")
            }
            sb.appendLine()
        }

        // 3. 生成切割与识别代码
        if (segConfig != null) {
            sb.appendLine("// 3. 配置切割参数")
            // 直接序列化 Config 对象
            // 因为您加了 @Serializable，这里会生成标准的 JSON
            val configJson = json.encodeToString(SegmentationConfig.serializer(), segConfig)
            sb.appendLine("const config: SegmentationConfig = $configJson;")
            sb.appendLine()

            if (!fontLib.isNullOrEmpty()) {
                sb.appendLine("// 4. 字库数据 (Hex压缩)")

                // 🔥 压缩逻辑：Binary -> Hex Map
                val compressedLib = fontLib.mapValues { (_, binStr) -> binaryStringToHex(binStr) }

                // 生成干净的 Map: { "汉": "HexStr", ... }
                val libJson = json.encodeToString(json.serializersModule.serializer(), compressedLib)
                sb.appendLine("const fontLibrary = $libJson;")

                // Rust 运行时会自动识别 Hex，无需解压代码
                sb.appendLine()
                sb.appendLine("// 5. 执行识别")
                sb.appendLine("const result = img.ocrGrid(config, fontLibrary, $minConf);")
                sb.appendLine($$"log(`识别结果: ${result}`);")
            }
        }

        // 4. 结尾清理建议
        sb.appendLine()
        sb.appendLine("// 提示: 如果在循环中使用，请记得手动回收图片资源")
        sb.appendLine("// img.recycle();")

        return sb.toString()
    }

    /**
     * 将任意 ImageFilter 转换为符合 TS 接口的 Wrapper JSON
     * TS 接口定义: type ImageFilterWrapper = { "Binarization": BinarizationFilter } | ...
     */
    @InternalSerializationApi
    private fun convertFilterToWrapperJson(filter: ImageFilter): String {
        // 1. 获取 Filter 的类名 (例如 "BinarizationFilter")
        val className = filter::class.simpleName ?: return "{}"

        // 2. 推导 TS 中的 Key (例如 "Binarization")
        // 约定：Kotlin 类名去掉 "Filter" 后缀即为 TS Key
        val keyName = className.removeSuffix("Filter")

        // 3. 序列化 Filter 内容本身
        // 使用反射获取该实例具体的 Serializer (需要 @Serializable 支持)
        val serializer = filter::class.serializer()

        @Suppress("UNCHECKED_CAST")
        val filterJson = json.encodeToString(serializer as kotlinx.serialization.KSerializer<Any>, filter)

        // 4. 手动包裹一层，构造成 Wrapper 结构
        // 最终输出: { "Binarization": { "mode": "Otsu", ... } }
        return """{ "$keyName": $filterJson }"""
    }
}