/*
 * ⚠️ THIS FILE IS AUTO-GENERATED BY RUST
 * ⚠️ DO NOT EDIT MANUALLY
 * Run `cargo run --bin gen_ts_types ` to update this file.
 */

/* eslint-disable */

export type Rect = { left: number, top: number, width: number, height: number, };

export type ColorRule = { id: bigint, target_hex: string, bias_hex: string, is_enabled: boolean, };

export type GridParams = { x: number, y: number, w: number, h: number, col_gap: number, row_gap: number, col_count: number, row_count: number, };

export type ProcessedImage = { width: number, height: number, pixels: Array<number>, };

export type SegmentationMode = "FixedGrid" | "Projection" | "ConnectedComp";

export type SegmentationConfig = { mode: SegmentationMode, padding: number, min_width: number, min_height: number, max_width: number, max_height: number, merge_distance: number, start_x: number, start_y: number, cell_width: number, cell_height: number, col_count: number, row_count: number, col_gap: number, row_gap: number, split_rows: boolean, split_cols: boolean, projection_threshold: number, };

export type ImageFilterWrapper = { "Binarization": BinarizationFilter } | { "Posterization": PosterizationFilter } | { "MultiColor": MultiColorFilter } | { "Grayscale": GrayscaleFilter } | { "RemoveNoise": RemoveNoiseFilter } | { "RemoveLines": RemoveLinesFilter } | { "ExtractContours": ExtractContoursFilter } | { "ExtractBlobs": ExtractBlobsFilter } | { "Deskew": DeskewFilter } | { "Rotation": RotationFilter } | { "BlackWhiteInvert": BlackWhiteInvertFilter } | { "Morphology": MorphologyFilter } | { "SmartLayout": SmartLayoutFilter } | { "AutoCrop": AutoCropFilter } | { "ResizeScale": ResizeScaleFilter } | { "ExtendCrop": ExtendCropFilter } | { "Denoise": DenoiseFilter };

