// This file is auto-generated by Rust. Do not edit.

export type Action = { "module": "Touch", "action": TouchAction } | { "module": "Vision", "action": VisionAction } | { "module": "Device", "action": DeviceAction } | { "module": "Control", "action": ControlAction };
export type MacroConfig = { loop_count: number, use_root: boolean, actions: Array<Action>, };
