use super::*;
use std::fs::{self};
use std::path::Path;
use ts_rs::TS;

// 🔥 在这里定义常量，想怎么改就怎么改
const TS_OUTPUT_PATH: &str = "../script_template/src/types/touch-helper.d.ts";

#[test]
fn export_all_types() {
    // 1. 收集所有需要导出的类型定义
    // Struct::decl() 会返回该结构体的 TypeScript 定义字符串
    let mut ts_content = String::from("// This file is auto-generated by Rust. Do not edit.\n\n");
    ts_content.push_str("export ");
    ts_content.push_str(&Action::decl());
    ts_content.push('\n');

    ts_content.push_str("export ");
    ts_content.push_str(&MacroConfig::decl());
    ts_content.push('\n');

    // 如果你有更多结构体，继续 push...
    // ts_content.push_str(&AnotherStruct::decl());

    // 2. 写入文件
    let path = Path::new(TS_OUTPUT_PATH);

    // 确保父目录存在
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).unwrap();
    }

    fs::write(path, ts_content).expect("Failed to write TypeScript definitions");

    println!("✅ TypeScript types exported to: {}", TS_OUTPUT_PATH);
}
