use crate::constants::SIGNAL_BYTE;

use super::*;
use std::fs::{self, File};
use std::io::Write;
use std::path::Path;
use ts_rs::TS;

// 🔥 在这里定义常量，想怎么改就怎么改
const TS_OUTPUT_PATH: &str = "../script_template/src/types/touch-helper.d.ts";
// 🔥 新增：Android Java 常量输出路径
// 注意：这个路径是相对于 rust_core 目录的
const JAVA_OUTPUT_PATH: &str =
    "../android/server/src/main/java/org/eu/freex/server/bind/GeneratedConstants.java";

#[test]
fn export_all() {
    export_ts_types();
    export_java_constants();
}

fn export_ts_types() {
    // 1. 收集所有需要导出的类型定义
    // Struct::decl() 会返回该结构体的 TypeScript 定义字符串
    let mut ts_content = String::from("// This file is auto-generated by Rust. Do not edit.\n\n");
    ts_content.push_str("export ");
    ts_content.push_str(&Action::decl());
    ts_content.push('\n');

    ts_content.push_str("export ");
    ts_content.push_str(&MacroConfig::decl());
    ts_content.push('\n');

    // 如果你有更多结构体，继续 push...
    // ts_content.push_str(&AnotherStruct::decl());

    // 2. 写入文件
    let path = Path::new(TS_OUTPUT_PATH);

    // 确保父目录存在
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).unwrap();
    }

    fs::write(path, ts_content).expect("Failed to write TypeScript definitions");

    println!("✅ TypeScript types exported to: {}", TS_OUTPUT_PATH);
}

// 🔥 新增：生成 Java 常量文件
fn export_java_constants() {
    let path = Path::new(JAVA_OUTPUT_PATH);

    // 自动创建目录（如果不存在）
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).unwrap();
    }

    let mut file = File::create(path).expect("Failed to create Java constants file");

    // 拼接 Java 代码
    // 注意：package 名要和你的 Java 目录对应
    let java_content = format!(
        r#"package org.eu.freex.server;

/**
 * Auto-generated by Rust (rust_core/src/export.rs).
 * DO NOT EDIT THIS FILE MANUALLY.
 * 修改源头: rust_core/src/constants.rs
 */
public class GeneratedConstants {{
    public static final String SHARED_FILE_PATH = "{shared_path}";
    // 使用十六进制格式化，并在 Java 中保留注释说明大小
    public static final byte SIGNAL_BYTE = (byte) {signal_byte};
    public static final int SHARED_MEMORY_SIZE = {mem_size}; // {mem_size_desc}
}}
"#,
        shared_path = SHARED_FILE_PATH,
        // 🔥 修改点 1: 使用 0x{:02X} 强制输出十六进制 (例如 0xAA)
        signal_byte = format!("0x{:02X}", SIGNAL_BYTE),
        // 🔥 修改点 2: 保持数字，但在后面加个注释显示计算逻辑，或者直接输出原值
        mem_size = SHARED_MEMORY_SIZE,
        // (可选) 如果想更直观，可以加个描述字符串参数
        mem_size_desc = format!("{} MB", SHARED_MEMORY_SIZE / (1024 * 1024)),
    );

    file.write_all(java_content.as_bytes()).unwrap();
    println!("✅ Java constants generated at: {}", JAVA_OUTPUT_PATH);
}
